name: Lint Commit Messages
on: pull_request

jobs:
  commitlint:
    runs-on:  [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-11, macos-arm-oss ]
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
