name: Publish

on:
  push:
    branches:
      - docs
  workflow_call:

jobs:
  launch:
    runs-on:  [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-11, macos-arm-oss ]
    steps:
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/${{ secrets.BUILDER }}/dispatches \
            -d '{"event_type":"deploy", "client_payload":{"branch": "${{ github.ref_name }}"}}'
