name: "Style Lint"

on:
  push:
    branches: ["master"]
    paths: ["_sass/**/*.scss"]
  pull_request:
    paths: ["_sass/**/*.scss"]

jobs:
  stylelint:
    runs-on:  [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-11, macos-arm-oss ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm i
      - run: npm test
